version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /share
      - ./docker/mysql/volumes:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c /app/config/unicorn.rb
    net:
      - sushi
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    volumes_from:
      - datastore
    depends_on:
      - db
    links:
      - db
      - db:database
      - db:mysql
    extends:
      file: ./docker/mysql/password.yml
      service: password
    stdin: true
    tty: true
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    net:
      - sushi
    ports:
      - '3306:3306'
    volumes_from:
      - datastore
    depends_on:
      - datastore
    extends:
      file: ./docker/mysql/password.yml
      service: password
    stdin: true
    tty: true
