default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: anicap_development

test:
  <<: *default
  database: anicap_test

production:
  <<: *default
  database: anicap_production
